GET http://localhost:9001/sample/

###

GET http://localhost:9001/user/

###

GET http://localhost:9001/all/

###

POST http://localhost:9001/add/
Content-Type: application/json

{
    "name" : "Ram",
    "todo": "GET JOB",
    "isChecked" : false
}